// client/src/components/OceanBackground.tsx
import { useEffect, useRef } from 'react';
import { WAVE_THEMES } from '@lyrika/shared';
import { OceanRenderer, webglAvailable } from '../bg/ocean';
import { useSettings } from '../state/settings';

export function OceanBackground(): JSX.Element {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const rendererRef = useRef<OceanRenderer | null>(null);

  const preset = useSettings((s) => s.wavePreset);
  const waveHeight = useSettings((s) => s.waveHeight);
  const reactivity = useSettings((s) => s.reactivity);
  const ecoMode = useSettings((s) => s.ecoMode);

  const theme = WAVE_THEMES[preset];
  const use3d = !ecoMode;

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!use3d || !canvas || !webglAvailable()) return;

    const renderer = new OceanRenderer(canvas, {
      theme: WAVE_THEMES[useSettings.getState().wavePreset],
      waveHeight: useSettings.getState().waveHeight * 3.2,
      reactivity: useSettings.getState().reactivity,
    });
    rendererRef.current = renderer;

    const resize = () => renderer.resize(canvas.clientWidth, canvas.clientHeight);
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    return () => {
      observer.disconnect();
      renderer.dispose();
      rendererRef.current = null;
    };
  }, [use3d]);

  useEffect(() => {
    rendererRef.current?.update({ theme, waveHeight: waveHeight * 3.2, reactivity });
  }, [theme, waveHeight, reactivity]);

  return (
    <div
      className="ocean"
      aria-hidden
      style={
        {
          '--fog': theme.fog,
          '--surface': theme.surface,
          '--atmosphere': theme.atmosphere,
        } as React.CSSProperties
      }
    >
      <div className="ocean__sky" />
      {use3d ? (
        <canvas ref={canvasRef} className="ocean__canvas" />
      ) : (
        <>
          <div className="ocean__arc ocean__arc--far" />
          <div className="ocean__arc ocean__arc--near" />
        </>
      )}
      <div className="ocean__scrim" />
    </div>
  );
}

// spike/solid-stage/src/OceanBackground.tsx
import { onCleanup, onMount, type JSX } from 'solid-js';
import { WAVE_THEMES } from '@lyrika/shared';
import { OceanRenderer, webglAvailable } from './bg/ocean';

const THEME = WAVE_THEMES.calm;

/**
 * Solid port of client/src/components/OceanBackground.tsx. React's
 * `useRef` + `useEffect(() => { ...; return cleanup }, [])` maps almost 1:1
 * onto Solid's `let canvas!: HTMLCanvasElement` (bound via `ref`) plus
 * `onMount` / `onCleanup` — no dependency array to get wrong, since `onMount`
 * only ever runs once by definition.
 *
 * This mounts the copied, unmodified `ocean.ts`, which reads the shared
 * `audioLevel.value` object every frame in its own rAF loop — entirely
 * outside Solid's signal graph, same as it's outside React's state today.
 * That's done criterion #4: it should animate and never fight Solid's own
 * rendering.
 */
export function OceanBackground(): JSX.Element {
  let canvas!: HTMLCanvasElement;
  let renderer: OceanRenderer | null = null;
  let observer: ResizeObserver | null = null;

  onMount(() => {
    if (!webglAvailable()) return;

    renderer = new OceanRenderer(canvas, {
      theme: THEME,
      waveHeight: 0.62 * 3.2,
      reactivity: 0.45,
    });

    const resize = () => renderer?.resize(canvas.clientWidth, canvas.clientHeight);
    resize();
    observer = new ResizeObserver(resize);
    observer.observe(canvas);
  });

  onCleanup(() => {
    observer?.disconnect();
    renderer?.dispose();
    renderer = null;
  });

  return (
    <div
      class="ocean"
      aria-hidden="true"
      style={{
        '--fog': THEME.fog,
        '--surface': THEME.surface,
        '--atmosphere': THEME.atmosphere,
      }}
    >
      <div class="ocean__sky" />
      <canvas ref={canvas} class="ocean__canvas" />
      <div class="ocean__scrim" />
    </div>
  );
}
