// client/src/components/TransportControls.tsx
import { usePlayer } from '../state/player';
import { useT } from '../state/settings';
import { Icon } from './Icon';

interface Props {
  size: 'lg' | 'md';
}

export function TransportControls({ size }: Props): JSX.Element {
  const playing = usePlayer((s) => s.playing);
  const status = usePlayer((s) => s.status);
  const toggle = usePlayer((s) => s.toggle);
  const next = usePlayer((s) => s.next);
  const previous = usePlayer((s) => s.previous);
  const queueLength = usePlayer((s) => s.queue.length);
  const t = useT();

  const loading = status === 'loading';
  const iconSize = size === 'lg' ? 18 : 16;

  return (
    <div className={`transport transport--${size}`}>
      <button type="button" className="transport__side" onClick={previous} aria-label="Назад">
        <Icon name="prev" size={size === 'lg' ? 15 : 13} />
      </button>
      <button
        type="button"
        className="transport__main"
        onClick={toggle}
        disabled={loading || status === 'idle'}
        aria-label={playing ? t('pause') : t('play')}
      >
        {loading ? (
          <span className="spinner spinner--dark" />
        ) : (
          <Icon name={playing ? 'pause' : 'play'} size={iconSize} />
        )}
      </button>
      <button
        type="button"
        className="transport__side"
        onClick={next}
        disabled={queueLength === 0}
        aria-label="Вперёд"
      >
        <Icon name="next" size={size === 'lg' ? 15 : 13} />
      </button>
    </div>
  );
}

// spike/solid-stage/src/TransportControls.tsx
import type { JSX } from 'solid-js';
import { playerState, toggle } from './store';

interface Props {
  size: 'lg' | 'md';
}

/**
 * Solid port of client/src/components/TransportControls.tsx. Queue is out of
 * scope for this spike, so prev/next stay visually present but inert.
 *
 * NOTE the props access below: `props.size`, never `const { size } = props`.
 * Destructuring at the top of the component reads `size` once at call time
 * and detaches it from Solid's reactivity — see docs/frontend-framework-
 * comparison.md for the before/after on this exact component.
 */
export function TransportControls(props: Props): JSX.Element {
  const loading = () => playerState.status === 'loading';
  const iconSize = () => (props.size === 'lg' ? 18 : 16);

  return (
    <div class={`transport transport--${props.size}`}>
      <button type="button" class="transport__side" disabled aria-label="Назад">
        ⏮
      </button>
      <button
        type="button"
        class="transport__main"
        onClick={toggle}
        disabled={loading() || playerState.status === 'idle'}
        aria-label={playerState.playing ? 'Пауза' : 'Играть'}
      >
        {loading() ? (
          <span class="spinner spinner--dark" />
        ) : (
          <span style={{ 'font-size': `${iconSize()}px` }}>{playerState.playing ? '⏸' : '▶'}</span>
        )}
      </button>
      <button type="button" class="transport__side" disabled aria-label="Вперёд">
        ⏭
      </button>
    </div>
  );
}
